export const fileFormats = [
    {
        Category: 'Audio',
        Type: '.aac',
        Name: 'AAC audio',
        Description: 'audio/aac',
    },
    {
        Category: 'Document',
        Type: '.abw',
        Name: 'AbiWord document',
        Description: 'application/x-abiword',
    },
    {
        Category: 'Other',
        Type: '.arc',
        Name: 'Archive document (multiple files embedded)',
        Description: 'application/x-freearc',
    },
    {
        Category: 'Video',
        Type: '.avi',
        Name: 'AVI: Audio Video Interleave',
        Description: 'video/x-msvideo',
    },
    {
        Category: 'Other',
        Type: '.azw',
        Name: 'Amazon Kindle eBook format',
        Description: 'application/vnd.amazon.ebook',
    },
    {
        Category: 'Other',
        Type: '.bin',
        Name: 'Any kind of binary data',
        Description: 'application/octet-stream',
    },
    {
        Category: 'Other',
        Type: '.bmp',
        Name: 'Windows OS/2 Bitmap Graphics',
        Description: 'image/bmp',
    },
    {
        Category: 'Zip',
        Type: '.bz',
        Name: 'BZip archive',
        Description: 'application/x-bzip',
    },
    {
        Category: 'Zip',
        Type: '.bz2',
        Name: 'BZip2 archive',
        Description: 'application/x-bzip2',
    },
    {
        Category: 'Other',
        Type: '.cda',
        Name: 'CD audio',
        Description: 'application/x-cdf',
    },
    {
        Category: 'Other',
        Type: '.csh',
        Name: 'C-Shell script',
        Description: 'application/x-csh',
    },
    {
        Category: 'Other',
        Type: '.css',
        Name: 'Cascading Style Sheets (CSS)',
        Description: 'text/css',
    },
    {
        Category: 'Spreadsheet',
        Type: '.csv',
        Name: 'Comma-separated values (CSV)',
        Description: 'text/csv',
    },
    {
        Category: 'Document',
        Type: '.doc',
        Name: 'Microsoft Word',
        Description: 'application/msword',
    },
    {
        Category: 'Document',
        Type: '.docx',
        Name: 'Microsoft Word (OpenXML)',
        Description:
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    },
    {
        Category: 'Other',
        Type: '.eot',
        Name: 'MS Embedded OpenType fonts',
        Description: 'application/vnd.ms-fontobject',
    },
    {
        Category: 'Other',
        Type: '.epub',
        Name: 'Electronic publication (EPUB)',
        Description: 'application/epub+zip',
    },
    {
        Category: 'Other',
        Type: '.gz',
        Name: 'GZip Compressed Archive',
        Description: 'application/gzip',
    },
    {
        Category: 'Image',
        Type: '.gif',
        Name: 'Graphics Interchange Format (GIF)',
        Description: 'image/gif',
    },
    {
        Category: 'Other',
        Type: '.htm, .html',
        Name: 'HyperText Markup Language (HTML)',
        Description: 'text/html',
    },
    {
        Category: 'Other',
        Type: '.ico',
        Name: 'Icon format',
        Description: 'image/vnd.microsoft.icon',
    },
    {
        Category: 'Other',
        Type: '.ics',
        Name: 'iCalendar format',
        Description: 'text/calendar',
    },
    {
        Category: 'Other',
        Type: '.jar',
        Name: 'Java Archive (JAR)',
        Description: 'application/java-archive',
    },
    {
        Category: 'Image',
        Type: '.jpeg, .jpg',
        Name: 'JPEG images',
        Description: 'image/jpeg',
    },
    {
        Category: 'Other',
        Type: '.js',
        Name: 'JavaScript',
        Description:
            'text/javascript (Specifications: HTML and its reasoning, and IETF)',
    },
    {
        Category: 'Other',
        Type: '.json',
        Name: 'JSON format',
        Description: 'application/json',
    },
    {
        Category: 'Other',
        Type: '.jsonld',
        Name: 'JSON-LD format',
        Description: 'application/ld+json',
    },
    {
        Category: 'Other',
        Type: '.mid, .midi',
        Name: 'Musical Instrument Digital Interface (MIDI)',
        Description: 'audio/midi audio/x-midi',
    },
    {
        Category: 'Other',
        Type: '.mjs',
        Name: 'JavaScript module',
        Description: 'text/javascript',
    },
    {
        Category: 'Audio',
        Type: '.mp3',
        Name: 'MP3 audio',
        Description: 'audio/mpeg',
    },
    {
        Category: 'Video',
        Type: '.mp4',
        Name: 'MP4 video',
        Description: 'video/mp4',
    },
    {
        Category: 'Video',
        Type: '.mpeg',
        Name: 'MPEG Video',
        Description: 'video/mpeg',
    },
    {
        Category: 'Other',
        Type: '.mpkg',
        Name: 'Apple Installer Package',
        Description: 'application/vnd.apple.installer+xml',
    },
    {
        Category: 'Other',
        Type: '.odp',
        Name: 'OpenDocument presentation document',
        Description: 'application/vnd.oasis.opendocument.presentation',
    },
    {
        Category: 'Other',
        Type: '.ods',
        Name: 'OpenDocument spreadsheet document',
        Description: 'application/vnd.oasis.opendocument.spreadsheet',
    },
    {
        Category: 'Other',
        Type: '.odt',
        Name: 'OpenDocument text document',
        Description: 'application/vnd.oasis.opendocument.text',
    },
    {
        Category: 'Audio',
        Type: '.oga',
        Name: 'OGG audio',
        Description: 'audio/ogg',
    },
    {
        Category: 'Video',
        Type: '.ogv',
        Name: 'OGG video',
        Description: 'video/ogg',
    },
    {
        Category: 'Other',
        Type: '.ogx',
        Name: 'OGG',
        Description: 'application/ogg',
    },
    {
        Category: 'Other',
        Type: '.opus',
        Name: 'Opus audio',
        Description: 'audio/opus',
    },
    {
        Category: 'Other',
        Type: '.otf',
        Name: 'OpenType font',
        Description: 'font/otf',
    },
    {
        Category: 'Image',
        Type: '.png',
        Name: 'Portable Network Graphics',
        Description: 'image/png',
    },
    {
        Category: 'PDF',
        Type: '.pdf',
        Name: 'Adobe Portable Document Format (PDF)',
        Description: 'application/pdf',
    },
    {
        Category: 'Other',
        Type: '.php',
        Name: 'Hypertext Preprocessor (Personal Home Page)',
        Description: 'application/x-httpd-php',
    },
    {
        Category: 'Document',
        Type: '.ppt',
        Name: 'Microsoft PowerPoint',
        Description: 'application/vnd.ms-powerpoint',
    },
    {
        Category: 'Document',
        Type: '.pptx',
        Name: 'Microsoft PowerPoint (OpenXML)',
        Description:
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    },
    {
        Category: 'Other',
        Type: '.rar',
        Name: 'RAR archive',
        Description: 'application/vnd.rar',
    },
    {
        Category: 'Other',
        Type: '.rtf',
        Name: 'Rich Text Format (RTF)',
        Description: 'application/rtf',
    },
    {
        Category: 'Other',
        Type: '.sh',
        Name: 'Bourne shell script',
        Description: 'application/x-sh',
    },
    {
        Category: 'Image',
        Type: '.svg',
        Name: 'Scalable Vector Graphics (SVG)',
        Description: 'image/svg+xml',
    },
    {
        Category: 'Other',
        Type: '.swf',
        Name: 'Small web format (SWF) or Adobe Flash document',
        Description: 'application/x-shockwave-flash',
    },
    {
        Category: 'Other',
        Type: '.tar',
        Name: 'Tape Archive (TAR)',
        Description: 'application/x-tar',
    },
    {
        Category: 'Image',
        Type: '.tif, .tiff',
        Name: 'Tagged Image File Format (TIFF)',
        Description: 'image/tiff',
    },
    {
        Category: 'Image',
        Type: '.ts',
        Name: 'MPEG transport stream',
        Description: 'video/mp2t',
    },
    {
        Category: 'Document',
        Type: '.ttf',
        Name: 'TrueType Font',
        Description: 'font/ttf',
    },
    {
        Category: 'Document',
        Type: '.txt',
        Name: 'Text, (generally ASCII or ISO 8859-n)',
        Description: 'text/plain',
    },
    {
        Category: 'Other',
        Type: '.vsd',
        Name: 'Microsoft Visio',
        Description: 'application/vnd.visio',
    },
    {
        Category: 'Audio',
        Type: '.wav',
        Name: 'Waveform Audio Format',
        Description: 'audio/wav',
    },
    {
        Category: 'Audio',
        Type: '.weba',
        Name: 'WEBM audio',
        Description: 'audio/webm',
    },
    {
        Category: 'Video',
        Type: '.webm',
        Name: 'WEBM video',
        Description: 'video/webm',
    },
    {
        Category: 'Image',
        Type: '.webp',
        Name: 'WEBP image',
        Description: 'image/webp',
    },
    {
        Category: 'Other',
        Type: '.woff',
        Name: 'Web Open Font Format (WOFF)',
        Description: 'font/woff',
    },
    {
        Category: 'Other',
        Type: '.woff2',
        Name: 'Web Open Font Format (WOFF)',
        Description: 'font/woff2',
    },
    {
        Category: 'Other',
        Type: '.xhtml',
        Name: 'XHTML',
        Description: 'application/xhtml+xml',
    },
    {
        Category: 'Spreadsheet',
        Type: '.xls',
        Name: 'Microsoft Excel',
        Description: 'application/vnd.ms-excel',
    },
    {
        Category: 'Spreadsheet',
        Type: '.xlsx',
        Name: 'Microsoft Excel (OpenXML)',
        Description:
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    },
    {
        Category: 'Other',
        Type: '.xml',
        Name: 'XML',
        Description:
            'application/xml is recommended as of RFC 7303 (section 4.1), but text/xml is still used sometimes. You can assign a specific MIME type to a file with .xml extension depending on how its contents are meant to be interpreted. For instance, an Atom feed is application/atom+xml, but application/xml serves as a valid default.',
    },
    {
        Category: 'Other',
        Type: '.xul',
        Name: 'XUL',
        Description: 'application/vnd.mozilla.xul+xml',
    },
    {
        Category: 'Zip',
        Type: '.zip',
        Name: 'ZIP archive',
        Description: 'application/zip',
    },
    {
        Category: 'Video',
        Type: '.3gp',
        Name: '3GPP audio/video container',
        Description: "video/3gpp; audio/3gpp if it doesn't contain video",
    },
    {
        Category: 'Video',
        Type: '.3g2',
        Name: '3GPP2 audio/video container',
        Description: "video/3gpp2; audio/3gpp2 if it doesn't contain video",
    },
    {
        Category: 'Zip',
        Type: '.7z',
        Name: '7-zip archive',
        Description: 'application/x-7z-compressed',
    },
    {
        Category: 'Model',
        Type: '.stl',
        Name: 'STL',
        Description: 'application/x-7z-compressed',
    },
    {
        Category: 'Model',
        Type: '.SLDPRT',
        Name: 'SLDPRT',
        Description: 'Solidworks Part',
    },
    {
        Category: 'Model',
        Type: '.SLDRW',
        Name: 'SLDRW',
        Description: 'Solidworks Drawing',
    },
];
